name: Somi test
on:
    workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: ./
            id: issue
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              title: Test Issue
              body: Test issue body
              assignees: |
                Milos Marinkovic
          - run: echo ${{ steps.issue.outputs.issue }}
